version: '3.8'

services:
  classifier_service:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DB_NAME="YOUR_DB_NAME"
    ports:
      - "5623:5623"
    volumes:
      - .:/app
    command: python main.py
